# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Grade_Calculator(object):
    def setupUi(self, Grade_Calculator):
        Grade_Calculator.setObjectName("Grade_Calculator")
        Grade_Calculator.resize(337, 292)
        Grade_Calculator.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.gridLayout = QtWidgets.QGridLayout(Grade_Calculator)
        self.gridLayout.setObjectName("gridLayout")
        self.output = QtWidgets.QLabel(Grade_Calculator)
        self.output.setMaximumSize(QtCore.QSize(16777215, 50))
        self.output.setText("")
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 5, 0, 1, 2)
        self.in_points_label = QtWidgets.QLabel(Grade_Calculator)
        self.in_points_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.in_points_label.setObjectName("in_points_label")
        self.gridLayout.addWidget(self.in_points_label, 0, 0, 1, 1)
        self.new_points = QtWidgets.QSpinBox(Grade_Calculator)
        self.new_points.setMaximum(2000)
        self.new_points.setSingleStep(10)
        self.new_points.setObjectName("new_points")
        self.gridLayout.addWidget(self.new_points, 1, 1, 1, 1)
        self.out_point_label = QtWidgets.QLabel(Grade_Calculator)
        self.out_point_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.out_point_label.setObjectName("out_point_label")
        self.gridLayout.addWidget(self.out_point_label, 0, 1, 1, 1)
        self.select_summative = QtWidgets.QRadioButton(Grade_Calculator)
        self.select_summative.setObjectName("select_summative")
        self.gridLayout.addWidget(self.select_summative, 3, 1, 1, 1)
        self.select_formative = QtWidgets.QRadioButton(Grade_Calculator)
        self.select_formative.setCheckable(True)
        self.select_formative.setChecked(False)
        self.select_formative.setObjectName("select_formative")
        self.gridLayout.addWidget(self.select_formative, 4, 1, 1, 1)
        self.total_cat_points = QtWidgets.QSpinBox(Grade_Calculator)
        self.total_cat_points.setMaximum(2000)
        self.total_cat_points.setSingleStep(100)
        self.total_cat_points.setObjectName("total_cat_points")
        self.gridLayout.addWidget(self.total_cat_points, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Grade_Calculator)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.not_changed_points = QtWidgets.QDoubleSpinBox(Grade_Calculator)
        self.not_changed_points.setObjectName("not_changed_points")
        self.gridLayout.addWidget(self.not_changed_points, 1, 0, 1, 1)

        self.retranslateUi(Grade_Calculator)
        QtCore.QMetaObject.connectSlotsByName(Grade_Calculator)

    def retranslateUi(self, Grade_Calculator):
        _translate = QtCore.QCoreApplication.translate
        Grade_Calculator.setWindowTitle(_translate("Grade_Calculator", "Grade_Calculator"))
        self.in_points_label.setText(_translate("Grade_Calculator", "Starting points:"))
        self.out_point_label.setText(_translate("Grade_Calculator", "Points added:"))
        self.select_summative.setText(_translate("Grade_Calculator", "Summative"))
        self.select_formative.setText(_translate("Grade_Calculator", "Formative"))
        self.label.setText(_translate("Grade_Calculator", "total points in catagory:"))
